FROM ubuntu:latest
LABEL "Training.name"="Docker Introduction"
LABEL "Training.location"="Mumbai"
LABEL website="ourowntestdemo.com"
LABEL desc="This is docker tutorial with \
mahindra teams"
LABEL tutorial1="Docker" tutorial2="LABEL INSTRUCTION"