FROM alpine:3.16

LABEL maintainer="bootlabs"

RUN apk add --update 
RUN apk add curl
RUN rm -rf /var/cache/apk/

##############Multiple Run #############

# RUN apk add --update && \
# 	apk add curl  && \  
# 	rm -rf /var/cache/apk/