FROM alpine:3.16

LABEL maintainer="bootlabs"

# WORKDIR /opt

####################################
# RUN echo "Welcome to Training Labs" > opt.txt
# WORKDIR folder1
# RUN echo "Welcome to Training Labs" > folder1.txt
# WORKDIR folder2
# RUN echo "Welcome to Training Labs" > folder2.txt

###########Absolute Path############

# WORKDIR /opt/folder1
# RUN echo "Welcome to Training Labs" > opt.txt
# WORKDIR /var/tmp/

##########Environment Variables path ########


ENV DIRPATH /myfolder
WORKDIR $DIRPATH